# Generated by Django 5.2.6 on 2025-09-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('P', 'PENDENTE'), ('A', 'ANDAMENTO'), ('C', 'CONCLUIDO')], default='P', max_length=1)),
                ('data_criacao', models.DateField(auto_now=True)),
            ],
        ),
    ]
